//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentoo.Domain.Shared.Localization.Global {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rentoo.Domain.Shared.Localization.Global.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        public static string Accepted {
            get {
                return ResourceManager.GetString("Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Notes.
        /// </summary>
        public static string AdditionalNotes {
            get {
                return ResourceManager.GetString("AdditionalNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Review.
        /// </summary>
        public static string AddReview {
            get {
                return ResourceManager.GetString("AddReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air Condition.
        /// </summary>
        public static string AirCondition {
            get {
                return ResourceManager.GetString("AirCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Request.
        /// </summary>
        public static string ApplicationRequest {
            get {
                return ResourceManager.GetString("ApplicationRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availability.
        /// </summary>
        public static string Availability {
            get {
                return ResourceManager.GetString("Availability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back To Home.
        /// </summary>
        public static string BackToHome {
            get {
                return ResourceManager.GetString("BackToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car.
        /// </summary>
        public static string Car {
            get {
                return ResourceManager.GetString("Car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Profile.
        /// </summary>
        public static string ClientProfile {
            get {
                return ResourceManager.GetString("ClientProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Information.
        /// </summary>
        public static string ContactInformation {
            get {
                return ResourceManager.GetString("ContactInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Reviews.
        /// </summary>
        public static string CustomerReviews {
            get {
                return ResourceManager.GetString("CustomerReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Documents.
        /// </summary>
        public static string DeleteDocuments {
            get {
                return ResourceManager.GetString("DeleteDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Address.
        /// </summary>
        public static string DeliveryAddress {
            get {
                return ResourceManager.GetString("DeliveryAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Information.
        /// </summary>
        public static string DocumentInformation {
            get {
                return ResourceManager.GetString("DocumentInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Status.
        /// </summary>
        public static string DocumentStatus {
            get {
                return ResourceManager.GetString("DocumentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Year.
        /// </summary>
        public static string FactoryYear {
            get {
                return ResourceManager.GetString("FactoryYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel Type.
        /// </summary>
        public static string FuelType {
            get {
                return ResourceManager.GetString("FuelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to km.
        /// </summary>
        public static string km {
            get {
                return ResourceManager.GetString("km", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En.
        /// </summary>
        public static string LanguageToggle {
            get {
                return ResourceManager.GetString("LanguageToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string lbAccept {
            get {
                return ResourceManager.GetString("lbAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string lbActions {
            get {
                return ResourceManager.GetString("lbActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string lbAddress {
            get {
                return ResourceManager.GetString("lbAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air Condition.
        /// </summary>
        public static string lbAirCondition {
            get {
                return ResourceManager.GetString("lbAirCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date.
        /// </summary>
        public static string lbBirthDate {
            get {
                return ResourceManager.GetString("lbBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rentals Cancelled.
        /// </summary>
        public static string lbcancelledRent {
            get {
                return ResourceManager.GetString("lbcancelledRent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car ID.
        /// </summary>
        public static string lbCarID {
            get {
                return ResourceManager.GetString("lbCarID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cars.
        /// </summary>
        public static string lbCars {
            get {
                return ResourceManager.GetString("lbCars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Cars.
        /// </summary>
        public static string lbCarsCount {
            get {
                return ResourceManager.GetString("lbCarsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cars Documents.
        /// </summary>
        public static string lbCarsDocuments {
            get {
                return ResourceManager.GetString("lbCarsDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string lbChangePassword {
            get {
                return ResourceManager.GetString("lbChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Photo.
        /// </summary>
        public static string lbChangePhoto {
            get {
                return ResourceManager.GetString("lbChangePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string lbColor {
            get {
                return ResourceManager.GetString("lbColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rentals Completed.
        /// </summary>
        public static string lbCompletedRent {
            get {
                return ResourceManager.GetString("lbCompletedRent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm New Password.
        /// </summary>
        public static string lbConfirmNewPassword {
            get {
                return ResourceManager.GetString("lbConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string lbConfirmPassword {
            get {
                return ResourceManager.GetString("lbConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string lbCreate {
            get {
                return ResourceManager.GetString("lbCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Admin.
        /// </summary>
        public static string lbCreatenewAdmin {
            get {
                return ResourceManager.GetString("lbCreatenewAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rentals In Progress.
        /// </summary>
        public static string lbCurrentRentels {
            get {
                return ResourceManager.GetString("lbCurrentRentels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string lbDashboard {
            get {
                return ResourceManager.GetString("lbDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string lbDelete {
            get {
                return ResourceManager.GetString("lbDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Address.
        /// </summary>
        public static string lbDeliveryAddress {
            get {
                return ResourceManager.GetString("lbDeliveryAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string lbDetails {
            get {
                return ResourceManager.GetString("lbDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string lbEndDate {
            get {
                return ResourceManager.GetString("lbEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory Year.
        /// </summary>
        public static string lbFactoryYear {
            get {
                return ResourceManager.GetString("lbFactoryYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string lbFirstName {
            get {
                return ResourceManager.GetString("lbFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel.
        /// </summary>
        public static string lbFuel {
            get {
                return ResourceManager.GetString("lbFuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string lbLastName {
            get {
                return ResourceManager.GetString("lbLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Image.
        /// </summary>
        public static string lbLicenseImage {
            get {
                return ResourceManager.GetString("lbLicenseImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Number.
        /// </summary>
        public static string lbLicenseNumber {
            get {
                return ResourceManager.GetString("lbLicenseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string lbLogin {
            get {
                return ResourceManager.GetString("lbLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string lbLogout {
            get {
                return ResourceManager.GetString("lbLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mileage.
        /// </summary>
        public static string lbMileage {
            get {
                return ResourceManager.GetString("lbMileage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string lbModel {
            get {
                return ResourceManager.GetString("lbModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National ID.
        /// </summary>
        public static string lbNationalID {
            get {
                return ResourceManager.GetString("lbNationalID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National ID Image.
        /// </summary>
        public static string lbNationalIDImage {
            get {
                return ResourceManager.GetString("lbNationalIDImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string lbNewPassword {
            get {
                return ResourceManager.GetString("lbNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string lbNext {
            get {
                return ResourceManager.GetString("lbNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Name.
        /// </summary>
        public static string lbOwnerName {
            get {
                return ResourceManager.GetString("lbOwnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string lbOwners {
            get {
                return ResourceManager.GetString("lbOwners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Owners.
        /// </summary>
        public static string lbOwnersCount {
            get {
                return ResourceManager.GetString("lbOwnersCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owners List.
        /// </summary>
        public static string lbOwnersList {
            get {
                return ResourceManager.GetString("lbOwnersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave blank if you don&apos;t want to change your password..
        /// </summary>
        public static string lbPass {
            get {
                return ResourceManager.GetString("lbPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string lbPassword {
            get {
                return ResourceManager.GetString("lbPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rentals Pending.
        /// </summary>
        public static string lbPendingRent {
            get {
                return ResourceManager.GetString("lbPendingRent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Verifications.
        /// </summary>
        public static string lbPendingverify {
            get {
                return ResourceManager.GetString("lbPendingverify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string lbPhoneNumber {
            get {
                return ResourceManager.GetString("lbPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pickup Address.
        /// </summary>
        public static string lbPickupAddress {
            get {
                return ResourceManager.GetString("lbPickupAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev.
        /// </summary>
        public static string lbPrev {
            get {
                return ResourceManager.GetString("lbPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string lbProfile {
            get {
                return ResourceManager.GetString("lbProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Picture.
        /// </summary>
        public static string lbProfilePicture {
            get {
                return ResourceManager.GetString("lbProfilePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string lbRegister {
            get {
                return ResourceManager.GetString("lbRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string lbReject {
            get {
                return ResourceManager.GetString("lbReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        public static string lbremember {
            get {
                return ResourceManager.GetString("lbremember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rentels.
        /// </summary>
        public static string lbRentels {
            get {
                return ResourceManager.GetString("lbRentels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Rentels.
        /// </summary>
        public static string lbRentelsCount {
            get {
                return ResourceManager.GetString("lbRentelsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renter.
        /// </summary>
        public static string lbRenter {
            get {
                return ResourceManager.GetString("lbRenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renters.
        /// </summary>
        public static string lbRenters {
            get {
                return ResourceManager.GetString("lbRenters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Renters.
        /// </summary>
        public static string lbRentersCount {
            get {
                return ResourceManager.GetString("lbRentersCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Car Document.
        /// </summary>
        public static string lbReviewCarDocument {
            get {
                return ResourceManager.GetString("lbReviewCarDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviewed At.
        /// </summary>
        public static string lbReviewedAt {
            get {
                return ResourceManager.GetString("lbReviewedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Renter Document.
        /// </summary>
        public static string lbReviewRenterDocument {
            get {
                return ResourceManager.GetString("lbReviewRenterDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string lbRole {
            get {
                return ResourceManager.GetString("lbRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string lbSaveChanges {
            get {
                return ResourceManager.GetString("lbSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seats.
        /// </summary>
        public static string lbSeats {
            get {
                return ResourceManager.GetString("lbSeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string lbShow {
            get {
                return ResourceManager.GetString("lbShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Car Documents.
        /// </summary>
        public static string lbShowCarDocuments {
            get {
                return ResourceManager.GetString("lbShowCarDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show User Documents.
        /// </summary>
        public static string lbShowUserDocuments {
            get {
                return ResourceManager.GetString("lbShowUserDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Don&apos;t have an account?.
        /// </summary>
        public static string lbsignup {
            get {
                return ResourceManager.GetString("lbsignup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string lbStartDate {
            get {
                return ResourceManager.GetString("lbStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string lbStatus {
            get {
                return ResourceManager.GetString("lbStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Admins.
        /// </summary>
        public static string lbSystemAdmin {
            get {
                return ResourceManager.GetString("lbSystemAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Price.
        /// </summary>
        public static string lbTotalPrice {
            get {
                return ResourceManager.GetString("lbTotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Documents.
        /// </summary>
        public static string lbUserDocuments {
            get {
                return ResourceManager.GetString("lbUserDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string lbUserName {
            get {
                return ResourceManager.GetString("lbUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Driver.
        /// </summary>
        public static string lbWithDriver {
            get {
                return ResourceManager.GetString("lbWithDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogIn.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Account.
        /// </summary>
        public static string MyAccount {
            get {
                return ResourceManager.GetString("MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY CARS.
        /// </summary>
        public static string MYCARS {
            get {
                return ResourceManager.GetString("MYCARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Requests.
        /// </summary>
        public static string MyRequests {
            get {
                return ResourceManager.GetString("MyRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t uploaded any documents yet. Please upload your documents below..
        /// </summary>
        public static string NoDocuments {
            get {
                return ResourceManager.GetString("NoDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No reviews yet for this car..
        /// </summary>
        public static string Noreviewsyetforthiscar {
            get {
                return ResourceManager.GetString("Noreviewsyetforthiscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Available.
        /// </summary>
        public static string NotAvailable {
            get {
                return ResourceManager.GetString("NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Information.
        /// </summary>
        public static string PersonalInformation {
            get {
                return ResourceManager.GetString("PersonalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pickup Address.
        /// </summary>
        public static string pickupAddress {
            get {
                return ResourceManager.GetString("pickupAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a comment.
        /// </summary>
        public static string Pleaseprovideacomment {
            get {
                return ResourceManager.GetString("Pleaseprovideacomment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a rating.
        /// </summary>
        public static string Pleaseselectarating {
            get {
                return ResourceManager.GetString("Pleaseselectarating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRICE PLANS.
        /// </summary>
        public static string PRICEPLANS {
            get {
                return ResourceManager.GetString("PRICEPLANS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Details.
        /// </summary>
        public static string RequestDetails {
            get {
                return ResourceManager.GetString("RequestDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request to Rent.
        /// </summary>
        public static string RequestToRent {
            get {
                return ResourceManager.GetString("RequestToRent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REVIEWS.
        /// </summary>
        public static string REVIEWS {
            get {
                return ResourceManager.GetString("REVIEWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search About Car.
        /// </summary>
        public static string SearchAboutCar {
            get {
                return ResourceManager.GetString("SearchAboutCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seats.
        /// </summary>
        public static string Seats {
            get {
                return ResourceManager.GetString("Seats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Your Car type.
        /// </summary>
        public static string SelectYourCartype {
            get {
                return ResourceManager.GetString("SelectYourCartype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Request.
        /// </summary>
        public static string SendRequest {
            get {
                return ResourceManager.GetString("SendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignUp.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifications.
        /// </summary>
        public static string Specifications {
            get {
                return ResourceManager.GetString("Specifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Review.
        /// </summary>
        public static string SubmitReview {
            get {
                return ResourceManager.GetString("SubmitReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This vehicle is currently unavailable for rental.
        /// </summary>
        public static string Thisvehicleiscurrentlyunavailableforrental {
            get {
                return ResourceManager.GetString("Thisvehicleiscurrentlyunavailableforrental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transmission.
        /// </summary>
        public static string Transmission {
            get {
                return ResourceManager.GetString("Transmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Documents.
        /// </summary>
        public static string UploadDocuments {
            get {
                return ResourceManager.GetString("UploadDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Dashboard.
        /// </summary>
        public static string UserDashboard {
            get {
                return ResourceManager.GetString("UserDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Driver.
        /// </summary>
        public static string WithDriver {
            get {
                return ResourceManager.GetString("WithDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Already Have Pending Request.
        /// </summary>
        public static string YouAlreadyHavePendingRequest {
            get {
                return ResourceManager.GetString("YouAlreadyHavePendingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any rental requests yet..
        /// </summary>
        public static string Youdon_thaveanyrentalrequestsyet_ {
            get {
                return ResourceManager.GetString("Youdon\'thaveanyrentalrequestsyet.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already reviewed this request.
        /// </summary>
        public static string Youhavealreadyreviewedthisrequest {
            get {
                return ResourceManager.GetString("Youhavealreadyreviewedthisrequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Documents.
        /// </summary>
        public static string YourDocuments {
            get {
                return ResourceManager.GetString("YourDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your documents are currently under review. You cannot update them until they are accepted..
        /// </summary>
        public static string YourdocumentsarecurrentlyunderreviewYoucannotupdatethemuntiltheyareaccepted_ {
            get {
                return ResourceManager.GetString("YourdocumentsarecurrentlyunderreviewYoucannotupdatethemuntiltheyareaccepted.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your documents have been rejected Please update them with the correct information.
        /// </summary>
        public static string YourdocumentshavebeenrejectedPleaseupdatethemwiththecorrectinformation {
            get {
                return ResourceManager.GetString("YourdocumentshavebeenrejectedPleaseupdatethemwiththecorrectinformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Information.
        /// </summary>
        public static string YourInformation {
            get {
                return ResourceManager.GetString("YourInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Profile Picture.
        /// </summary>
        public static string YourProfilePicture {
            get {
                return ResourceManager.GetString("YourProfilePicture", resourceCulture);
            }
        }
    }
}
